main: net.minelucky.vanish.GoodbyeGonePoof
name: '${name}'
version: '${version}'
authors: [ "MineLucky Development Team" ]
description: '${description}'
softdepend:
  - 'DiscordSRV'
  - 'ProtocolLib'
  - 'PlaceholderAPI'
  - 'Essentials'