redis_uri: 'redis://localhost:6379'

# Leave sounds blank to disable them
# Example: command: ""
sounds:
    command: "ENTITY_EXPERIENCE_ORB_PICKUP"
    vanish: "ENTITY_EXPERIENCE_ORB_PICKUP"
    unvanish: "ENTITY_EXPERIENCE_ORB_PICKUP"

vanish:
    # Show players an actionbar when they are vanished
    actionbar: true

    # Should we change player type to spectator in tablist for players who have permission to see vanished players?
    # Note: Requires ProtocolLib in versions lower than 1.19
    see_as_spectator: true

    silent_open_container: true

    prevent:
        pickup: true
        block_break: false
        block_place: false
        interact: false