# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
config_version: 7
default_language: en_US

# Leave sounds blank to disable them
# Example: command: ""
sounds:
    command: "ENTITY_EXPERIENCE_ORB_PICKUP"
    vanish: "ENTITY_EXPERIENCE_ORB_PICKUP"
    unvanish: "ENTITY_EXPERIENCE_ORB_PICKUP"

vanish:
    # Show players an actionbar when they are vanished
    actionbar: true

    # Should we change player type to spectator in tablist for players who have permission to see vanished players?
    # Note: Requires ProtocolLib in versions lower than 1.19
    see_as_spectator: true

    # Should vanished players be protected from all damage sources?
    invincible: true

    silent_open_container: true

    prevent:
        pickup: true
        block_break: false
        block_place: false
        interact: false

hooks:
    essentials:
        force_prevent_private_messages: false